"""openeval.event_table — the LaTeX audit fragment."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from openeval import event_table


def _run(audited: Path, registry: Path, tmp_path: Path, *extra: str) -> str:
    out = tmp_path / "events.tex"
    event_table.main(["--replay", str(audited), "--registry", str(registry),
                      "--out", str(out), *extra])
    return out.read_text()


def test_one_table_per_evm_chain_all_events_present(
        audited: Path, world: dict, tmp_path: Path) -> None:
    tex = _run(audited, world["registry"], tmp_path)
    assert tex.count(r"\begin{table}") == 2
    assert r"\label{tab:events-ethereum}" in tex and r"\label{tab:events-tron}" in tex
    for name in ("Alpha Exchange Breach", "Beta Bridge Exploit", "Gamma Drainer",
                 "Delta OTC Desk", "Epsilon Laundry"):
        assert name in tex
    assert "Zeta" not in tex  # bitcoin is not part of the EVM audit tables


def test_undetected_events_print_a_dash_and_dates_are_legend_coded(
        audited: Path, world: dict, tmp_path: Path) -> None:
    tex = _run(audited, world["registry"], tmp_path)
    beta_row = next(line for line in tex.splitlines() if line.startswith("Beta"))
    assert "---" in beta_row          # undetected
    assert "& o &" in beta_row        # audited OFAC date
    alpha_row = next(line for line in tex.splitlines() if line.startswith("Alpha"))
    assert "& s &" in alpha_row       # scraped
    assert "161.0" in alpha_row


def test_expected_event_count_gate(audited: Path, world: dict, tmp_path: Path) -> None:
    _run(audited, world["registry"], tmp_path, "--expect-evm-events", "5")
    with pytest.raises(SystemExit, match="expected 4 EVM events, got 5"):
        _run(audited, world["registry"], tmp_path, "--expect-evm-events", "4")


def test_provenance_lines_are_a_passthrough(audited: Path, world: dict, tmp_path: Path) -> None:
    tex = _run(audited, world["registry"], tmp_path,
               "--provenance-line", "% custom line one",
               "--provenance-line", "% custom line two")
    assert tex.startswith("% custom line one\n% custom line two\n")
    default = _run(audited, world["registry"], tmp_path)
    assert default.startswith("% AUTO-GENERATED by openeval.event_table.")


def test_latex_special_characters_are_escaped(tmp_path: Path) -> None:
    replay = {"events": [{
        "name": "Weird & Co 100%_x #1 {v2} $5 ~a^b",
        "chain": "ethereum", "publication_date": "2024-01-01",
        "publication_source": "scraped", "n_addresses": 1, "n_in_graph": 1,
        "n_flagged_fin": 1, "lead_days_fin": 5.0}]}
    registry = [{"name": "Weird & Co 100%_x #1 {v2} $5 ~a^b", "category": "cat_a & b"}]
    rp, rg = tmp_path / "r.json", tmp_path / "reg.json"
    rp.write_text(json.dumps(replay))
    rg.write_text(json.dumps(registry))
    tex = _run(rp, rg, tmp_path)
    row = next(line for line in tex.splitlines() if line.startswith("Weird"))
    assert r"\&" in row and r"\%" in row and r"\_" in row and r"\#" in row
    assert r"\{v2\}" in row and r"\$5" in row
    assert r"\textasciitilde{}" in row and r"\textasciicircum{}" in row
    # no unescaped specials survive outside the escapes we just checked
    assert " & " in row  # the column separators themselves stay


def test_unknown_publication_source_is_a_named_error(tmp_path: Path) -> None:
    replay = {"events": [{
        "name": "X", "chain": "ethereum", "publication_date": "2024-01-01",
        "publication_source": "carrier_pigeon", "n_addresses": 1, "n_in_graph": 1,
        "n_flagged_fin": 0, "lead_days_fin": None}]}
    registry = [{"name": "X", "category": "c"}]
    rp, rg = tmp_path / "r.json", tmp_path / "reg.json"
    rp.write_text(json.dumps(replay))
    rg.write_text(json.dumps(registry))
    with pytest.raises(SystemExit, match="carrier_pigeon"):
        _run(rp, rg, tmp_path)


def test_escape_function_ordering(tmp_path: Path) -> None:
    # A backslash must come out as \textbackslash{} with its braces INTACT —
    # the naive replace-backslash-first order hands them to the brace step.
    assert event_table.tex_escape("a\\b") == r"a\textbackslash{}b"
    assert event_table.tex_escape("50%_x") == r"50\%\_x"
    assert event_table.tex_escape("\\{}") == r"\textbackslash{}\{\}"
    # a NUL in the input must not collide with the sentinel
    assert event_table.tex_escape("a\x00b\\c") == r"ab\textbackslash{}c"
