"""Emit the per-event audit table of an EVM lead-time replay as a LaTeX fragment.

Inputs (read-only):
  --replay    replay artefact (openeval.leadtime / openeval.date_audit
              output shape) — per-event rows
  --registry  the event registry the replay was built from — per-event
              category

Output: one .tex file with a table per chain (Ethereum, Tron), sorted by
publication date, plus the consistency counts a reviewer can check
against the prose that quotes the replay (events, detections, date-source
split, per-chain medians) printed to stdout.

The generated header comment is a provenance passthrough: pass one
--provenance-line per comment line to record where the inputs came from
(defaults to a neutral marker). The table content itself is derived
entirely from the artefacts.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import median

# publication_source -> single-letter legend of the "Date" column.
DATE_SOURCE = {
    "scraped": "s",
    "scrape": "s",
    "ofac_scraped_d7": "o",
    "event_date_proxy_+3d": "p",
    "event_date_fallback": "p",
}


def tex_escape(s: str) -> str:
    # Backslash goes through a char-free sentinel: replacing it directly
    # with \textbackslash{} FIRST would hand its braces to the brace step,
    # and doing it last would mangle the backslashes the other escapes
    # introduce. A NUL in the input would collide with the sentinel, so it
    # is dropped first (it is not printable LaTeX either way).
    s = s.replace("\x00", "").replace("\\", "\x00")
    for a, b in (("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s.replace("\x00", r"\textbackslash{}")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--replay", required=True, type=Path)
    ap.add_argument("--registry", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--expect-evm-events", type=int, default=None,
                    help="fail unless the replay carries exactly this many EVM events")
    ap.add_argument("--provenance-line", action="append", default=None,
                    help="comment line(s) written at the top of the fragment; repeatable")
    args = ap.parse_args(argv)

    lt = json.loads(args.replay.read_text())
    cat = {e["name"]: e["category"] for e in json.loads(args.registry.read_text())}

    evm = [e for e in lt["events"] if e["chain"] in ("ethereum", "tron")]
    if args.expect_evm_events is not None and len(evm) != args.expect_evm_events:
        raise SystemExit(f"expected {args.expect_evm_events} EVM events, got {len(evm)}")

    lines: list[str] = list(args.provenance_line or [
        "% AUTO-GENERATED by openeval.event_table.",
        "% Do not edit by hand; re-run the producer instead.",
    ])
    counts: dict[str, int] = {}
    n_detected = 0
    for chain, label in (("ethereum", "Ethereum"), ("tron", "Tron")):
        rows = [e for e in evm if e["chain"] == chain]
        rows.sort(key=lambda e: e["publication_date"])
        lines += [
            r"\begin{table}[!htbp]",
            r"\centering",
            (rf"\caption{{The {len(rows)} {label} registry events of the replay"
             r" (Sect.~\ref{sec:leadtime}). ``Date'' column: s = publication"
             r" date scraped from the public source; o = OFAC action date"
             r" from the registry date audit; p = proxy (event date"
             + (" + 3 days" if chain == "ethereum" else "") + r"). ``Addr'' ="
             r" in-graph / listed addresses; ``Flag'' = addresses flagged by"
             r" the fincrime head at the $10^{-3}$ population budget;"
             r" ``Lead'' = days from first"
             r" on-chain appearance of the earliest flagged address to"
             r" publication (--- = event not detected).}"),
            rf"\label{{tab:events-{chain}}}",
            r"\setlength{\tabcolsep}{3pt}",
            r"\tiny",
            r"\begin{tabular}{p{4.5cm}p{2.5cm}ccccr}",
            r"\toprule",
            r"Event & Category & Publication & Date & Addr & Flag & Lead (d) \\",
            r"\midrule",
        ]
        for e in rows:
            if e["publication_source"] not in DATE_SOURCE:
                raise SystemExit(
                    f"unknown publication_source {e['publication_source']!r} on "
                    f"{e['name']!r}; the Date-column legend knows: {sorted(DATE_SOURCE)}")
            src = DATE_SOURCE[e["publication_source"]]
            counts[src] = counts.get(src, 0) + 1
            detected = e["lead_days_fin"] is not None
            n_detected += detected
            lead = f"{e['lead_days_fin']:.1f}" if detected else "---"
            lines.append(
                f"{tex_escape(e['name'])} & {tex_escape(cat[e['name']])} & "
                f"{e['publication_date']} & {src} & "
                f"{e['n_in_graph']}/{e['n_addresses']} & "
                f"{e['n_flagged_fin']} & {lead} \\\\"
            )
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]

    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {len(evm)} events, detected {n_detected}, "
          f"date sources {counts} (s=scraped, o=OFAC audit, p=proxy)")
    med = sorted(e["n_in_graph"] for e in evm)[len(evm) // 2]
    print(f"in-graph per event: min {min(e['n_in_graph'] for e in evm)} "
          f"median {med} max {max(e['n_in_graph'] for e in evm)}")

    # Consistency counts for the prose that quotes the replay.
    det = [e for e in evm if e["lead_days_fin"] is not None]
    print(f"non-positive leads: {sum(1 for e in det if e['lead_days_fin'] <= 0)} "
          f"of {len(det)} detections")
    for chain in ("ethereum", "tron"):
        dc = [e for e in det if e["chain"] == chain]
        if dc:
            print(f"{chain}: detected {len(dc)}, "
                  f"median lead {median(e['lead_days_fin'] for e in dc):.1f}, "
                  f"positive {sum(1 for e in dc if e['lead_days_fin'] > 0)}")


if __name__ == "__main__":
    main()
